#!/usr/bin/env python3
"""Fichas de padecimientos y tratamientos (CPT condicion/tratamiento) redactadas a partir del cuestionario
de la Dra. (briefing-privado/fichas-latest.json, confirmado 2026-10-09) y del briefing general.
Siempre se crean/actualizan en DRAFT con estado_medico=medical_review_required; el gate del plugin impide
publicarlas sin aprobación médica. La Dra. revisa y aprueba cada una en wp-admin.

Reglas de redacción (DISCOVERY.md, OD-004, OD-009): tono cercano y claro («tú»), sin cifras ni promesas de
resultado, sin indicaciones individuales, sin nombres de terceros. Lo que la Dra. REFIERE se describe como
referencia, no como oferta. Fuentes: propuestas (SMORL/CCC, AAO-HNS, AASM); la Dra. las valida."""
import json, pathlib

NOTA = "Borrador redactado a partir del cuestionario de la Dra. (9 de octubre de 2026). Pendiente de su revisión y aprobación médica."

# ---- Fuentes propuestas (la Dra. valida; URLs a páginas institucionales estables) ----
SMORL = dict(titulo="Sociedad Mexicana de Otorrinolaringología y Cirugía de Cabeza y Cuello (SMORL y CCC)", autor="SMORL y CCC", anio="", url="https://smorlccc.org.mx/", tipo="sociedad")
AAO = lambda t, a: dict(titulo=f"Clinical Practice Guideline: {t}", autor="American Academy of Otolaryngology–Head and Neck Surgery (AAO-HNS)", anio=a, url="https://www.entnet.org/quality-practice/quality-products/clinical-practice-guidelines/", tipo="guia")
AASM = lambda t, a: dict(titulo=t, autor="American Academy of Sleep Medicine (AASM)", anio=a, url="https://aasm.org/clinical-resources/practice-standards/practice-guidelines/", tipo="guia")
EPOS = dict(titulo="European Position Paper on Rhinosinusitis and Nasal Polyps (EPOS 2020)", autor="Fokkens WJ et al., Rhinology", anio="2020", url="https://epos2020.com/", tipo="guia")
ARIA = dict(titulo="Allergic Rhinitis and its Impact on Asthma (ARIA) Guidelines", autor="ARIA / OMS", anio="2020", url="https://www.euforea.eu/aria", tipo="guia")

# ---- Textos reutilizables según lo que la Dra. hace en consultorio e indica fuera ----
DX_OIDO = "<p>La valoración se hace en el consultorio: la Dra. revisa tu historia, explora el oído con otoscopia y, cuando hace falta ver con más detalle o limpiar el conducto, con microscopía de oído. En la mayoría de los casos esto basta para saber qué está pasando y empezar el tratamiento ese mismo día.</p>"
DX_AUDIO = "<p>Si hace falta medir cuánto escuchas, la Dra. indica una audiometría, que se realiza en un gabinete especializado. Con el resultado en mano define el tratamiento y, si tu caso requiere cirugía de oído, te orienta y te refiere con un cirujano otológico de confianza.</p>"
DX_NARIZ = "<p>En consultorio la Dra. explora la nariz y realiza una <strong>endoscopia nasal</strong>: una cámara delgada que permite ver el tabique, los cornetes y la salida de los senos paranasales sin molestias importantes. Cuando se necesita conocer la anatomía con precisión o planear una cirugía, indica una tomografía de senos paranasales, que se realiza en un centro de imagen.</p>"
DX_GARGANTA = "<p>La valoración se hace en consultorio con exploración y, cuando hace falta ver la laringe y la faringe por dentro, con una <strong>laringoscopia</strong> o endoscopia flexible, que dura unos minutos y se tolera bien.</p>"
DX_SUENO = "<p>La Dra. explora la nariz, la boca y la garganta y realiza una endoscopia nasal y de la vía aérea para ver dónde se estrecha el paso del aire. Si sospecha apnea, indica un <strong>estudio del sueño en casa</strong> (poligrafía respiratoria) que ella misma interpreta. En casos seleccionados realiza una endoscopia de sueño (DISE) en quirófano o indica una polisomnografía en laboratorio.</p>"
REFIERE_CX_OIDO = "Si el tratamiento requiere cirugía de oído, la Dra. te explica las opciones y te refiere con un cirujano otológico de confianza."

cond = []
def C(slug, titulo, area, zona, resumen, html, sintomas, causas, cuando, diagnostico, enfoque, faq, fuentes, tratamientos, relacionados=()):
    cond.append(dict(slug=slug, titulo=titulo, area=area, zona=zona, resumen=resumen, html=html, sintomas=sintomas, causas=causas,
                     cuando_consultar=cuando, diagnostico=diagnostico, enfoque_dra=enfoque, faq=[dict(pregunta=p, respuesta=r) for p, r in faq],
                     fuentes=fuentes, tratamientos=list(tratamientos), relacionados=list(relacionados), nota=NOTA))

trat = []
def T(slug, titulo, area, zona, tipo, oferta, resumen, html, candidatos, estudio_previo, como, recuperacion, riesgos, enfoque, faq, fuentes, resuelve, relacionados=()):
    trat.append(dict(slug=slug, titulo=titulo, area=area, zona=zona, tipo=tipo, oferta=oferta, resumen=resumen, html=html, candidatos=candidatos,
                     estudio_previo=estudio_previo, como_se_realiza=como, recuperacion=recuperacion, riesgos_y_alternativas=riesgos, enfoque_dra=enfoque,
                     faq=[dict(pregunta=p, respuesta=r) for p, r in faq], fuentes=fuentes, resuelve=list(resuelve), relacionados=list(relacionados), nota=NOTA))

# =====================================================================  OÍDO  =====
C("otitis", "Otitis", "orl", "oido",
  "Infección o inflamación del oído, frecuente en niños pero también en adultos. Puede afectar el oído externo (el conducto) o el oído medio (detrás del tímpano).",
  "<p>«Otitis» significa inflamación del oído, y hay dos tipos que vemos todos los días en consulta. La <strong>otitis externa</strong> afecta el conducto auditivo, es típica después de nadar o de limpiarse con cotonetes, y duele sobre todo al tocar o jalar la oreja. La <strong>otitis media</strong> ocurre detrás del tímpano, casi siempre después de un resfriado, y es la causa más común de dolor de oído en niños.</p><p>En los niños también es frecuente la <strong>otitis media con líquido</strong>: el oído no duele, pero queda líquido atrapado que hace que escuchen menos. Cuando se repite o se prolonga, afecta el lenguaje y el rendimiento escolar, y por eso vale la pena revisarla.</p>",
  ["Dolor de oído, a veces intenso", "Sensación de oído tapado o escuchar menos", "Fiebre, sobre todo en niños", "Salida de líquido o pus por el oído", "En bebés: llanto, irritabilidad y llevarse la mano al oído"],
  ["Infecciones respiratorias (resfriados, gripe) que inflaman la trompa de Eustaquio", "Agua que queda en el conducto después de nadar", "Lesiones al limpiar el oído con cotonetes u objetos", "Alergias y adenoides grandes en niños", "Piel sensible del conducto (eccema, dermatitis)"],
  ["Dolor intenso o que dura más de dos días", "Fiebre alta o salida de líquido por el oído", "Infecciones de oído que se repiten en el año", "Un niño que escucha menos o habla menos de lo esperado", "Dolor de oído con inflamación detrás de la oreja: valoración urgente"],
  DX_OIDO + "<p>Cuando hay salida de secreción, la Dra. puede aspirarla y limpiar el conducto en el mismo consultorio para que el tratamiento llegue a donde debe. " + REFIERE_CX_OIDO + "</p>",
  "<p>Una otitis bien tratada se cura sin dejar secuelas. Lo que la Dra. busca evitar es el ciclo de infecciones repetidas: por eso, además de tratar el episodio, revisa la nariz, las adenoides y los hábitos de limpieza para atacar la causa. Atiende a pacientes desde los primeros meses de vida.</p>",
  [("¿La otitis se contagia?", "No. Lo que se contagia es el resfriado que la desencadena. La infección del oído en sí no pasa de una persona a otra."),
   ("¿Puedo ponerme gotas que tengo en casa?", "Mejor no antes de que te revisen. Algunas gotas están contraindicadas si el tímpano está perforado, y eso solo se sabe explorando el oído."),
   ("¿Mi hijo puede nadar con otitis?", "Durante una otitis activa conviene evitar el agua. Cuando el oído sana, la Dra. te dice cuándo y cómo retomar la alberca.")],
  [AAO("Otitis Media with Effusion", "2016"), AAO("Acute Otitis Externa", "2014"), SMORL], [], ("tapon-de-cerumen", "hipoacusia"))

C("tapon-de-cerumen", "Tapón de cerumen", "orl", "oido",
  "Acumulación de cera que obstruye el conducto auditivo. El cerumen protege el oído; el problema aparece cuando se compacta, muchas veces por el uso de cotonetes.",
  "<p>El cerumen no es suciedad. Es una capa protectora que la piel del conducto produce para atrapar polvo, repeler el agua y mantener a raya a bacterias y hongos. El oído se limpia solo: los movimientos de la mandíbula al hablar y masticar empujan la cera hacia afuera.</p><p>El <strong>tapón</strong> se forma cuando esa salida natural se interrumpe. La causa más frecuente es el cotonete, que empuja la cera hacia el fondo y la compacta contra el tímpano. También contribuyen los audífonos, los tapones para dormir o nadar, los conductos estrechos y la piel seca de las personas mayores.</p>",
  ["Sensación de oído tapado", "Escuchar menos de un lado", "Zumbido", "Molestia, picazón o sensación de presión", "Tos refleja o mareo leve en algunos casos"],
  ["Uso de cotonetes u objetos para limpiar el oído", "Audífonos, auriculares intrauriculares y tapones de uso frecuente", "Conductos auditivos estrechos o con vello abundante", "Piel seca del conducto, más común con la edad", "Agua que hincha la cera ya acumulada"],
  ["Oído tapado que no mejora en pocos días", "Dolor o pérdida de audición", "Antes de intentar retirarlo en casa, sobre todo si has tenido perforación o cirugía de oído", "Si usas audífonos o aparatos auditivos y notas que funcionan peor"],
  DX_OIDO + "<p>Si hay tapón, la Dra. lo retira en el mismo consultorio mediante lavado o aspiración bajo visión con microscopio, según el tipo de cera y la condición del tímpano. Suele resolverse en una sola visita.</p>",
  "<p>Retirar un tapón es rápido cuando lo hace quien ve lo que está haciendo. La Dra. prefiere la aspiración bajo microscopio porque permite limpiar sin lastimar la piel ni el tímpano, y aprovecha la visita para enseñarte cómo cuidar tus oídos y evitar que se repita.</p>",
  [("¿Cómo debo limpiarme los oídos?", "Solo la parte externa de la oreja, con la toalla al salir del baño. Nada debe entrar al conducto: ni cotonetes, ni llaves, ni velas. Si sientes el oído tapado, la revisión toma unos minutos."),
   ("¿Sirven las gotas para reblandecer la cera?", "Pueden ayudar en algunos casos, pero no sustituyen la revisión. Si el tapón es grande o el tímpano tiene alguna lesión, las gotas pueden empeorar la molestia."),
   ("¿Con qué frecuencia debo venir a limpieza?", "Depende de cada persona. Quienes usan audífonos o producen mucha cera suelen necesitar una revisión periódica; la Dra. te indica cada cuánto según tu caso.")],
  [AAO("Earwax (Cerumen Impaction)", "2017"), SMORL], [], ("otitis", "hipoacusia"))

C("hipoacusia", "Hipoacusia (pérdida de audición)", "orl", "oido",
  "Disminución de la audición en uno o ambos oídos, de aparición gradual o súbita. El otorrinolaringólogo identifica la causa y define el tratamiento médico, quirúrgico o de apoyo auditivo.",
  "<p>Escuchar menos no es solo cuestión de edad. La hipoacusia puede deberse a un problema mecánico en el oído externo o medio (cera, líquido, perforación, rigidez de los huesecillos), a un daño en el oído interno o en el nervio auditivo, o a una combinación de ambos. Cada tipo tiene un tratamiento distinto, y por eso el primer paso es saber de dónde viene.</p><p>Hay una forma que merece atención inmediata: la <strong>hipoacusia súbita</strong>, cuando en horas o pocos días dejas de escuchar de un oído. Es una situación en la que el tiempo cuenta, y conviene que te valoren pronto.</p>",
  ["Pedir que repitan lo que dicen, sobre todo con ruido de fondo", "Subir el volumen de la televisión o del teléfono", "Escuchar menos de un oído", "Zumbido o sensación de oído tapado", "En niños: no responder al nombre, retraso en el lenguaje o bajo rendimiento escolar"],
  ["Tapón de cerumen o líquido en el oído medio", "Otitis de repetición o perforación del tímpano", "Exposición prolongada al ruido", "Envejecimiento del oído interno (presbiacusia)", "Algunos medicamentos, infecciones y causas hereditarias"],
  ["Pérdida de audición repentina, en horas o días: valoración pronta", "Pérdida progresiva que afecta la vida diaria o el trabajo", "Pérdida de audición en niños, a cualquier edad", "Hipoacusia de un solo oído o acompañada de zumbido o vértigo"],
  "<p>La Dra. revisa tu historia y explora el oído con otoscopia y microscopía para descartar causas visibles, como cera, líquido o una perforación.</p>" + DX_AUDIO,
  "<p>Muchas pérdidas auditivas tienen solución, y otras se pueden compensar muy bien con un auxiliar auditivo bien indicado. El objetivo de la Dra. es que no te resignes: identificar la causa, tratar lo tratable y, cuando hace falta apoyo auditivo, orientarte para que la adaptación sea exitosa.</p>",
  [("¿La pérdida de audición se recupera?", "Depende de la causa. Si es por cera, líquido o infección, suele recuperarse con tratamiento. Si es del oído interno, el objetivo es detener el avance y compensarla con un auxiliar auditivo cuando conviene."),
   ("¿Necesito audífonos (auxiliares auditivos)?", "Solo si la audiometría muestra una pérdida que lo justifica y después de descartar causas tratables. La Dra. te orienta sobre el tipo adecuado y te acompaña en la adaptación."),
   ("¿A partir de qué edad se puede revisar la audición de un niño?", "Desde recién nacido. Existen pruebas para cada edad; si tienes dudas sobre cómo escucha tu hijo, no esperes a que crezca.")],
  [AAO("Sudden Hearing Loss", "2019"), AAO("Age-Related Hearing Loss", "2024"), SMORL], [], ("tapon-de-cerumen", "tinnitus", "otitis"))

C("tinnitus", "Tinnitus (acúfeno)", "orl", "oido",
  "Percepción de un zumbido, pitido o silbido sin una fuente externa de sonido. Tiene causas diversas y el primer paso es descartar las que tienen tratamiento.",
  "<p>El tinnitus o acúfeno es escuchar un sonido que no viene de afuera: un zumbido, un pitido, un siseo. Es muy frecuente y en la mayoría de las personas se relaciona con algún grado de pérdida auditiva, aunque también puede acompañar a un tapón de cerumen, a una otitis, a problemas de la mandíbula o al estrés y la falta de sueño.</p><p>No es una enfermedad en sí, sino un síntoma. Por eso la valoración se centra en encontrar su origen y en descartar las pocas causas que requieren estudio adicional, como el tinnitus de un solo oído o el que late al ritmo del pulso.</p>",
  ["Zumbido, pitido o silbido constante o intermitente", "Más notorio en silencio o por la noche", "Puede acompañarse de pérdida de audición o de oído tapado", "Dificultad para concentrarse o para conciliar el sueño"],
  ["Pérdida auditiva por edad o por exposición al ruido", "Tapón de cerumen, líquido o infección en el oído", "Algunos medicamentos", "Problemas de la articulación de la mandíbula o del cuello", "Estrés, ansiedad y mal descanso, que lo amplifican"],
  ["Tinnitus de un solo oído", "Aparición súbita o acompañada de pérdida de audición o vértigo", "Tinnitus que late con el pulso", "Cuando afecta el sueño, la concentración o el estado de ánimo"],
  DX_OIDO + DX_AUDIO,
  "<p>El tinnitus se puede manejar, y en muchos casos mejora cuando se trata la causa o se compensa la pérdida auditiva. La Dra. te explica de dónde viene el tuyo, te enseña estrategias para que deje de ocupar el centro de tu atención y, cuando el sueño está afectado, lo aborda también desde su formación en medicina del sueño.</p>",
  [("¿El tinnitus tiene cura?", "A veces desaparece al tratar la causa (cera, infección, líquido). Cuando se asocia a daño del oído interno, el objetivo es reducirlo y que deje de molestar, y eso se logra en la mayoría de los casos."),
   ("¿Es señal de algo grave?", "Casi nunca. Las señales que sí requieren estudio son el tinnitus de un solo oído, el que late con el pulso o el que aparece de golpe con pérdida de audición."),
   ("¿Por qué lo escucho más de noche?", "Porque en silencio no hay otros sonidos que lo enmascaren. Un ruido suave de fondo y una buena higiene de sueño suelen ayudar.")],
  [AAO("Tinnitus", "2014"), SMORL], [], ("hipoacusia", "tapon-de-cerumen"))

C("vertigo", "Vértigo", "orl", "oido",
  "Sensación de que todo gira, con frecuencia originada en el oído interno. Se diferencia del mareo inespecífico y se estudia con exploración y maniobras en consultorio.",
  "<p>Vértigo es la sensación de que tú o el entorno giran. No es lo mismo que «mareo» o inestabilidad: el vértigo verdadero suele venir del oído interno, donde está el órgano del equilibrio. La causa más común es el <strong>vértigo posicional</strong>, en el que pequeños cristales del oído interno se desplazan y provocan giros breves e intensos al mover la cabeza o acostarse.</p><p>Otras causas del oído son la neuritis vestibular, que produce un vértigo prolongado después de una infección viral, y la enfermedad de Ménière, con episodios de vértigo, zumbido y pérdida de audición. Distinguirlas se hace en consultorio con exploración y maniobras específicas.</p>",
  ["Sensación de giro al mover la cabeza, al acostarse o al voltear en la cama", "Náusea o vómito", "Inestabilidad al caminar", "Puede acompañarse de zumbido, oído tapado o pérdida de audición", "Movimientos involuntarios de los ojos durante la crisis"],
  ["Vértigo posicional paroxístico benigno (cristales desplazados en el oído interno)", "Neuritis vestibular tras una infección viral", "Enfermedad de Ménière", "Migraña vestibular", "Algunos medicamentos y causas del sistema nervioso (menos frecuentes)"],
  ["Primer episodio de vértigo", "Episodios que se repiten o que te impiden hacer tu vida normal", "Vértigo con pérdida de audición de un lado", "Vértigo con dolor de cabeza intenso, visión doble, dificultad para hablar o debilidad: urgencia"],
  "<p>La valoración se hace en el consultorio. La Dra. revisa cómo y cuándo aparece el vértigo, explora el oído y realiza maniobras de posición que reproducen el síntoma y permiten identificar su origen. En el vértigo posicional, la misma maniobra que lo diagnostica sirve para tratarlo.</p>" + DX_AUDIO.replace("define el tratamiento y, si", "define el tratamiento. Si hay signos que no corresponden al oído, indica una resonancia o te refiere con neurología. Si"),
  "<p>El vértigo asusta, pero la mayoría de las causas se resuelven bien. La Dra. dedica la consulta a entender tu episodio y a explorar con calma, porque en vértigo el diagnóstico está en la historia y en las maniobras, no en los estudios caros. Cuando el origen es posicional, el tratamiento se hace ahí mismo.</p>",
  [("¿Es vértigo o es mareo?", "Si sientes que todo gira, es vértigo y suele venir del oído. Si es una sensación de flotar, de cabeza vacía o de que te vas a desmayar, es mareo y tiene otras causas. La exploración ayuda a distinguirlos."),
   ("¿Las pastillas para el vértigo lo curan?", "Alivian la crisis, pero no corrigen la causa. En el vértigo posicional, lo que cura es la maniobra de reposición; en otras causas, el tratamiento depende del diagnóstico."),
   ("¿Puedo manejar si tengo vértigo?", "Durante una crisis o mientras no esté controlado, no. La Dra. te indicará cuándo es seguro retomar actividades.")],
  [AAO("Benign Paroxysmal Positional Vertigo", "2017"), AAO("Ménière's Disease", "2020"), SMORL], [], ("hipoacusia", "tinnitus"))

# ===================================================================== NARIZ =====
C("rinitis", "Rinitis", "orl", "nariz",
  "Inflamación de la mucosa nasal, alérgica o no alérgica. Produce nariz tapada, estornudos y escurrimiento, y afecta el sueño y la calidad de vida.",
  "<p>La rinitis es la inflamación del revestimiento interno de la nariz. La forma más conocida es la <strong>rinitis alérgica</strong>, desencadenada por ácaros, polen, mascotas u hongos, pero también existe la rinitis no alérgica, que reacciona a cambios de temperatura, olores fuertes, humo o ciertos medicamentos, incluidos los descongestionantes en spray cuando se usan muchos días seguidos.</p><p>Aunque suele verse como una molestia menor, la rinitis mal controlada altera el sueño, el rendimiento y, en niños, favorece la respiración por la boca y las otitis. Casi siempre se controla bien cuando se identifica el tipo y se trata con constancia.</p>",
  ["Nariz tapada, de forma constante o alternando de lado", "Estornudos en salva", "Escurrimiento nasal claro", "Picazón de nariz, ojos o paladar", "Respirar por la boca y ronquido, sobre todo en niños"],
  ["Alergia a ácaros, polen, mascotas u hongos", "Cambios de temperatura, humo, olores fuertes y contaminación", "Uso prolongado de descongestionantes en spray", "Cambios hormonales, como en el embarazo", "Crecimiento de los cornetes por inflamación crónica"],
  ["Síntomas la mayor parte del año", "Cuando afectan el sueño, el rendimiento escolar o el trabajo", "Si los medicamentos de venta libre no controlan los síntomas", "Nariz tapada que no mejora con tratamiento", "Si usas spray descongestionante a diario"],
  DX_NARIZ + "<p>Cuando conviene confirmar la alergia y saber a qué reaccionas, la Dra. indica pruebas de alergia, que se realizan en un laboratorio o con alergología.</p>",
  "<p>La rinitis se controla con un plan, no con un spray de emergencia. La Dra. combina tratamiento médico, medidas en casa y, cuando los cornetes han crecido tanto que ya no responden a medicamentos, valora una turbinoplastia para devolverte el paso del aire. Atiende rinitis en niños desde los primeros meses de vida.</p>",
  [("¿La rinitis alérgica se cura?", "La tendencia alérgica suele acompañarte, pero los síntomas se controlan muy bien con tratamiento constante y medidas en casa. En algunos casos la inmunoterapia (vacunas) reduce la sensibilidad con el tiempo."),
   ("¿Por qué el spray descongestionante ya no me hace efecto?", "Porque los descongestionantes en spray, usados más de unos días, inflaman la mucosa de rebote y crean dependencia. Hay que retirarlos con un plan y tratar la causa."),
   ("¿Cuándo se opera la rinitis?", "La rinitis en sí no se opera. Lo que se opera son los cornetes cuando crecieron tanto que obstruyen aun con tratamiento médico: es la turbinoplastia.")],
  [ARIA, AAO("Allergic Rhinitis", "2015"), SMORL], ["turbinoplastia"], ("sinusitis", "desviacion-de-tabique-nasal", "ronquido"))

C("sinusitis", "Sinusitis", "orl", "nariz",
  "Inflamación de los senos paranasales, aguda o crónica. Se valora la causa (infección, alergia, obstrucción anatómica, pólipos) con endoscopia nasal.",
  "<p>Los senos paranasales son cavidades llenas de aire dentro de los huesos de la cara, conectadas con la nariz por pequeñas aberturas. Cuando esas aberturas se tapan, el moco se acumula, se infecta y aparece la sinusitis. La <strong>sinusitis aguda</strong> sigue casi siempre a un resfriado y se cura en pocas semanas. La <strong>sinusitis crónica</strong> dura meses y suele tener detrás una causa que mantiene la obstrucción: alergia, tabique desviado, pólipos o una anatomía estrecha.</p><p>Muchas personas viven años con «gripa» que no se quita, dolor de cara y pérdida de olfato. La endoscopia nasal permite ver qué está pasando y romper ese ciclo.</p>",
  ["Presión o dolor en la cara, la frente o detrás de los ojos", "Nariz tapada y secreción espesa, por delante o hacia la garganta", "Pérdida o disminución del olfato", "Tos, sobre todo nocturna, y dolor de cabeza", "Mal aliento y sensación de fatiga"],
  ["Infecciones respiratorias virales que se complican", "Rinitis alérgica mal controlada", "Tabique desviado o cornetes grandes que bloquean el drenaje", "Pólipos nasales", "Problemas dentales en los molares superiores (menos frecuente)"],
  ["Síntomas que duran más de diez días o que empeoran después de haber mejorado", "Sinusitis que se repite varias veces al año", "Pérdida de olfato persistente", "Dolor de cara con fiebre alta, hinchazón alrededor del ojo o cambios en la visión: urgencia"],
  DX_NARIZ,
  "<p>La Dra. trata primero con medicamentos y lavados, y busca la causa que mantiene la inflamación. Si la sinusitis es crónica y no responde, o si hay pólipos o una obstrucción anatómica, ofrece la cirugía endoscópica nasal, que abre los senos por dentro de la nariz sin cicatrices externas.</p>",
  [("¿La sinusitis siempre necesita antibiótico?", "No. La mayoría de las sinusitis agudas son virales y mejoran con lavados nasales y tratamiento de los síntomas. El antibiótico se reserva para casos bacterianos, que la Dra. identifica en la exploración."),
   ("¿Necesito una tomografía?", "No siempre. La endoscopia en consultorio suele ser suficiente para el diagnóstico. La tomografía se indica cuando la sinusitis es crónica, hay sospecha de pólipos o se planea una cirugía."),
   ("¿Los lavados nasales sirven de verdad?", "Sí, son una de las medidas más efectivas y seguras. La Dra. te enseña cómo hacerlos bien para que ayuden y no molesten.")],
  [EPOS, AAO("Adult Sinusitis", "2015"), SMORL], ["cirugia-endoscopica-nasal"], ("rinitis", "polipos-nasales", "desviacion-de-tabique-nasal"))

C("desviacion-de-tabique-nasal", "Desviación del tabique nasal", "orl", "nariz",
  "El tabique separa las dos fosas nasales; cuando está desviado obstruye el paso del aire por uno o ambos lados y puede contribuir al ronquido.",
  "<p>El tabique es la pared de cartílago y hueso que divide la nariz en dos fosas. Pocas personas lo tienen perfectamente recto, y eso no es un problema. Lo es cuando la desviación es suficiente para que el aire no pase bien por uno o ambos lados: entonces respiras por la boca, duermes mal, roncas y tienes sinusitis con más frecuencia.</p><p>La desviación puede ser de nacimiento o consecuencia de un golpe, a veces en la infancia y olvidado. Lo importante es que tiene solución definitiva: la septoplastia corrige la desviación por dentro de la nariz, sin cambiar su forma externa.</p>",
  ["Nariz tapada de un lado o alternante", "Respirar por la boca, sobre todo al dormir", "Ronquido y sueño poco reparador", "Sinusitis de repetición", "Sangrados nasales frecuentes y resequedad", "Dolor de cabeza o presión facial en algunos casos"],
  ["Desarrollo desigual del cartílago y el hueso durante el crecimiento", "Golpes en la nariz, incluidos los de la infancia", "Fracturas nasales que consolidaron desviadas"],
  ["Obstrucción nasal constante o que te obliga a respirar por la boca", "Ronquido o mal descanso", "Sangrados nasales frecuentes", "Sinusitis que se repite", "Antes de cualquier cirugía de nariz, para valorar la función y la forma en conjunto"],
  DX_NARIZ,
  "<p>La Dra. valora la nariz completa, no solo el tabique: cornetes, válvula nasal y senos paranasales. Si la obstrucción tiene causa anatómica y no mejora con tratamiento médico, ofrece la septoplastia, sola o combinada con turbinoplastia, y cuando también quieres mejorar la forma de la nariz, lo planea como una rinoplastia funcional.</p>",
  [("¿Todos los tabiques desviados se operan?", "No. Solo cuando la desviación obstruye y los síntomas afectan tu vida. Muchas desviaciones no dan molestias y no necesitan nada."),
   ("¿La septoplastia cambia la forma de mi nariz?", "No. Se hace por dentro, sin incisiones externas. Si además quieres cambiar la forma, se puede planear una rinoplastia funcional en el mismo procedimiento."),
   ("¿Se puede operar a un adolescente?", "En general se prefiere esperar a que termine el crecimiento facial, salvo que la obstrucción sea importante. La Dra. lo valora caso por caso.")],
  [SMORL, AAO("Improving Nasal Form and Function after Rhinoplasty", "2017")], ["septoplastia", "rinoplastia", "turbinoplastia"], ("rinitis", "sinusitis", "ronquido"))

C("polipos-nasales", "Pólipos nasales", "orl", "nariz",
  "Crecimientos benignos de la mucosa nasal, asociados con inflamación crónica. Obstruyen la nariz y disminuyen el olfato.",
  "<p>Los pólipos nasales son como pequeñas uvas de mucosa inflamada que crecen dentro de la nariz y los senos paranasales. No son cáncer ni se transforman en él, pero sí obstruyen, quitan el olfato y mantienen una sinusitis crónica que no se va con nada. Se relacionan con inflamación persistente: asma, alergia, sensibilidad a la aspirina o una respuesta inflamatoria propia de cada persona.</p><p>El tratamiento combina medicamentos que reducen la inflamación y, cuando los pólipos ya ocupan demasiado espacio, cirugía endoscópica para retirarlos y abrir los senos. Como la tendencia a formarlos persiste, el seguimiento después de la cirugía es parte del tratamiento.</p>",
  ["Nariz tapada progresiva, de ambos lados", "Pérdida de olfato y del gusto", "Secreción nasal espesa o hacia la garganta", "Sensación de presión en la cara", "Ronquido y respiración por la boca"],
  ["Inflamación crónica de la mucosa nasal (rinosinusitis crónica)", "Asma y rinitis alérgica", "Sensibilidad a la aspirina y a antiinflamatorios", "Predisposición individual"],
  ["Obstrucción nasal que no mejora con tratamiento", "Pérdida de olfato", "Sinusitis crónica que se repite tras varios tratamientos", "Pólipo de un solo lado: siempre debe valorarse"],
  DX_NARIZ + "<p>La tomografía es parte habitual del estudio de los pólipos porque muestra hasta dónde llegan y permite planear la cirugía con seguridad.</p>",
  "<p>La Dra. plantea los pólipos como una condición crónica que se controla: primero con tratamiento médico, después con cirugía endoscópica cuando la obstrucción lo justifica, y siempre con seguimiento para que no vuelvan a crecer. El objetivo es que respires y recuperes el olfato, y que la mejoría dure.</p>",
  [("¿Los pólipos son peligrosos?", "No son cáncer. Lo que sí requiere valoración es un pólipo de un solo lado o con sangrado, para descartar otras lesiones."),
   ("¿Vuelven a salir después de la cirugía?", "Pueden volver porque la tendencia inflamatoria persiste. Por eso el seguimiento y el tratamiento de mantenimiento son parte del plan, y reducen mucho las recaídas."),
   ("¿Recuperaré el olfato?", "En muchos casos mejora de forma notable con el tratamiento y la cirugía. La Dra. te orienta sobre qué esperar según el tiempo que lleves sin oler.")],
  [EPOS, SMORL], ["cirugia-endoscopica-nasal"], ("sinusitis", "rinitis"))

C("epistaxis", "Sangrado nasal (epistaxis)", "orl", "nariz",
  "Sangrado por la nariz. La mayoría de los casos son leves y se originan en la parte anterior del tabique; se estudian cuando se repiten.",
  "<p>La nariz sangra con facilidad porque su mucosa es delgada y tiene muchos vasos pequeños, sobre todo en la parte delantera del tabique. Ahí se originan casi todos los sangrados: por resequedad, por rascarse, por un resfriado o por el clima seco y el aire acondicionado. Suelen detenerse con presión y no indican nada grave.</p><p>Vale la pena estudiar los sangrados que se repiten, los que son abundantes y los que aparecen en personas que toman anticoagulantes o tienen presión alta. En consultorio se identifica el punto de sangrado y, en muchos casos, se trata en la misma visita.</p>",
  ["Sangrado por una fosa nasal, a veces hacia la garganta", "Sangrado que se repite en días o semanas", "Sangrado tras resequedad, rascado o un resfriado", "Costras y resequedad en la nariz"],
  ["Resequedad de la mucosa por clima seco, calefacción o aire acondicionado", "Rascado o limpieza brusca de la nariz", "Resfriados, rinitis y uso de sprays nasales", "Tabique desviado con una zona expuesta al aire", "Presión arterial alta, anticoagulantes y, con menos frecuencia, alteraciones de la coagulación"],
  ["Sangrado abundante que no se detiene en 20 minutos con presión: urgencia", "Sangrados frecuentes, aunque sean pequeños", "Sangrado en personas que toman anticoagulantes o antiagregantes", "Sangrado en niños que se repite o de un solo lado con obstrucción"],
  DX_NARIZ.replace("Cuando se necesita conocer la anatomía con precisión o planear una cirugía, indica una tomografía de senos paranasales, que se realiza en un centro de imagen.", "Cuando los sangrados se repiten, indica estudios de laboratorio para revisar la coagulación y, si sospecha una causa dentro de la nariz que la endoscopia no aclara, una tomografía.") + "<p>Si se identifica el vaso que sangra, la Dra. puede cauterizarlo en consultorio con anestesia local.</p>",
  "<p>La Dra. te enseña primero qué hacer en casa cuando sangra la nariz, porque la mayoría de los episodios se controlan con presión bien aplicada. Después busca la causa y la trata: humedad, cuidado de la mucosa, cauterización del punto que sangra o corrección del tabique cuando es el origen.</p>",
  [("¿Qué hago mientras sangra?", "Siéntate, inclina la cabeza ligeramente hacia adelante y aprieta la parte blanda de la nariz con los dedos durante 10 a 15 minutos sin soltar. No eches la cabeza hacia atrás ni te acuestes."),
   ("¿Es normal que a mi hijo le sangre la nariz seguido?", "Es frecuente en niños por rascado y resequedad, y casi siempre es benigno. Si se repite mucho o es de un solo lado con la nariz tapada, conviene revisarlo."),
   ("¿Tengo que dejar mi anticoagulante?", "No lo suspendas por tu cuenta. La Dra. se coordina con tu médico tratante para decidir qué hacer según la causa y la frecuencia del sangrado.")],
  [AAO("Nosebleed (Epistaxis)", "2020"), SMORL], [], ("rinitis", "desviacion-de-tabique-nasal"))

# =================================================================== GARGANTA =====
C("amigdalitis", "Amigdalitis", "orl", "garganta",
  "Infección o inflamación de las amígdalas. Cuando se repite muchas veces al año o las amígdalas crecen demasiado, se valora el tratamiento quirúrgico.",
  "<p>Las amígdalas son dos masas de tejido linfático a los lados de la garganta que forman parte de las defensas, sobre todo en los primeros años de vida. La amigdalitis es su infección, casi siempre viral y, en algunos casos, por bacterias como el estreptococo. La mayoría de los episodios se resuelven con tratamiento médico.</p><p>Hay dos situaciones en las que el otorrinolaringólogo valora algo más: cuando las infecciones <strong>se repiten muchas veces al año</strong> y cuando las amígdalas, con o sin infección, <strong>crecen tanto que obstruyen</strong> la respiración al dormir, sobre todo en niños, y provocan ronquido, pausas y mal descanso.</p>",
  ["Dolor de garganta, a veces intenso al tragar", "Fiebre y malestar general", "Amígdalas grandes, rojas o con placas blancas", "Ganglios inflamados en el cuello", "Mal aliento, voz «de papa caliente» y, en niños, ronquido"],
  ["Virus respiratorios (la causa más común)", "Bacterias, sobre todo estreptococo", "Contacto cercano en guarderías y escuelas", "Crecimiento de amígdalas y adenoides en la infancia"],
  ["Varios episodios de amigdalitis en un año", "Amígdalas grandes con ronquido, pausas al dormir o respiración por la boca en niños", "Dificultad para respirar o para tragar", "Dolor de garganta intenso de un solo lado con dificultad para abrir la boca: urgencia", "Placas o fiebre que no mejoran con tratamiento"],
  DX_GARGANTA + "<p>Cuando se valora una cirugía de amígdalas y adenoides, la Dra. indica estudios de imagen solo si hacen falta para ver el tamaño de las adenoides o descartar otra causa de obstrucción. En niños con ronquido, puede sumar un estudio del sueño en casa.</p>",
  "<p>La Dra. trata la amigdalitis con medicamentos y reserva la cirugía para quien de verdad la necesita: infecciones repetidas que afectan la vida del niño o del adulto, o amígdalas que obstruyen el sueño. Explica a los padres con calma qué esperar antes, durante y después, porque un postoperatorio bien acompañado se lleva mucho mejor.</p>",
  [("¿Cuándo se deben operar las amígdalas?", "Cuando las infecciones son frecuentes y afectan la vida diaria, o cuando las amígdalas obstruyen la respiración durante el sueño. Las guías actuales dan criterios claros y la Dra. los revisa contigo."),
   ("¿Un niño sin amígdalas se enferma más?", "No. Las amígdalas son una pequeña parte del sistema de defensa; después de la cirugía los niños se defienden igual y, en general, se enferman menos de la garganta."),
   ("¿Cómo es el postoperatorio de amígdalas?", "Hay dolor de garganta por varios días, que se controla con analgésicos, hidratación y alimentos suaves y fríos. La Dra. entrega indicaciones por escrito y está disponible para dudas.")],
  [AAO("Tonsillectomy in Children", "2019"), SMORL], ["amigdalas-y-adenoides"], ("ronquido", "reflujo-laringofaringeo"))

C("reflujo-laringofaringeo", "Reflujo laringofaríngeo", "orl", "garganta",
  "El contenido del estómago llega a la garganta y la laringe e irrita la mucosa, a menudo sin acidez. Se le llama reflujo silencioso.",
  "<p>En el reflujo laringofaríngeo, pequeñas cantidades de contenido del estómago suben hasta la garganta y las cuerdas vocales, que son mucho más sensibles que el esófago. Por eso puede irritar sin que sientas agruras ni ardor: lo que notas es carraspera, sensación de «algo atorado», ronquera por las mañanas o tos que no se explica.</p><p>Se le llama reflujo silencioso porque muchas personas no se reconocen como pacientes de reflujo. El diagnóstico se apoya en los síntomas y en lo que la Dra. ve en la laringe, y el tratamiento combina cambios de hábitos y, cuando hace falta, medicamentos.</p>",
  ["Carraspera constante y necesidad de aclarar la garganta", "Sensación de nudo o de cuerpo extraño en la garganta", "Ronquera, sobre todo al despertar", "Tos crónica y seca", "Moco espeso en la garganta y, a veces, dificultad para tragar"],
  ["Relajación de las válvulas que separan el estómago del esófago y la garganta", "Comidas abundantes, tardías o acostarse poco después de comer", "Café, alcohol, tabaco, grasas, picante y bebidas gaseosas", "Sobrepeso y ropa ajustada", "Estrés y uso excesivo de la voz, que amplifican los síntomas"],
  ["Ronquera que dura más de tres semanas", "Carraspera o sensación de cuerpo extraño persistentes", "Tos crónica sin causa respiratoria", "Dificultad para tragar o dolor al tragar que no mejora", "Ronquera en fumadores: valoración sin demora"],
  DX_GARGANTA + "<p>La laringoscopia permite ver los signos de irritación en las cuerdas vocales y descartar otras causas de ronquera, que es lo más importante. En casos seleccionados la Dra. se coordina con gastroenterología para estudios del esófago.</p>",
  "<p>El reflujo silencioso mejora cuando se entiende. La Dra. dedica tiempo a explicarte qué lo provoca en tu caso y a construir un plan realista de hábitos, porque el medicamento sin cambios suele quedarse corto. Y si la voz es tu herramienta de trabajo, cuida ese aspecto con especial atención.</p>",
  [("¿Puedo tener reflujo si no tengo agruras?", "Sí. En el reflujo laringofaríngeo las agruras suelen faltar; los síntomas son de garganta y voz. Por eso muchas personas tardan en identificarlo."),
   ("¿Tengo que tomar medicamento de por vida?", "No necesariamente. Los medicamentos se usan por un periodo mientras los hábitos hacen su parte; después se reducen según la respuesta."),
   ("¿La sensación de nudo en la garganta es algo grave?", "Casi siempre se debe a irritación por reflujo o tensión muscular, pero la laringoscopia sirve justamente para confirmarlo y descartar otras causas.")],
  [AAO("Hoarseness (Dysphonia)", "2018"), SMORL], [], ("amigdalitis",))

# ===================================================================== SUEÑO =====
C("ronquido", "Ronquido", "sueno", "sueno",
  "El ronquido es el ruido que produce el aire al pasar por una vía aérea estrecha durante el sueño. Puede ser solo molesto o ser el signo visible de una apnea del sueño.",
  "<p>Roncar no es normal, aunque sea común. El ronquido aparece cuando el aire pasa con dificultad por una vía aérea que se estrecha al dormir: la nariz tapada, el paladar y la campanilla largos, las amígdalas grandes o la lengua que cae hacia atrás hacen vibrar los tejidos y producen el ruido.</p><p>Hay un <strong>ronquido primario</strong>, que es ruido sin pausas en la respiración y afecta sobre todo a quien duerme al lado, y un ronquido que es el síntoma visible de una <strong>apnea obstructiva del sueño</strong>, con pausas, caídas de oxígeno y un descanso que no repara. Saber cuál es el tuyo cambia por completo el tratamiento, y por eso la valoración empieza por ahí.</p>",
  ["Ronquido fuerte y frecuente, la mayoría de las noches", "Pausas en la respiración que otros notan", "Sueño poco reparador y cansancio al despertar", "Boca seca o dolor de cabeza por la mañana", "Somnolencia durante el día", "En niños: ronquido, respiración por la boca, sudoración nocturna y cambios en la conducta"],
  ["Obstrucción nasal (tabique desviado, rinitis, cornetes grandes)", "Paladar blando y campanilla largos o amígdalas grandes", "Sobrepeso y acumulación de grasa en el cuello", "Dormir boca arriba, alcohol y sedantes por la noche", "En niños: amígdalas y adenoides grandes"],
  ["Cuando la pareja o la familia notan pausas en la respiración", "Somnolencia durante el día o cansancio aunque duermas suficiente", "Ronquido en niños, a cualquier edad", "Ronquido que empezó o empeoró con el aumento de peso", "Presión alta difícil de controlar o despertares con sensación de ahogo"],
  DX_SUENO + "<p>Cuando la obstrucción es nasal y se plantea cirugía, la Dra. indica una tomografía o resonancia según el caso.</p>",
  "<p>El tratamiento depende de si hablamos de un ronquido primario o de uno secundario a apnea. Por eso la Dra. no trata «el ruido» sin antes saber qué hay detrás. Con el diagnóstico claro, las opciones van desde medidas y tratamiento nasal hasta cirugía del paladar o de la nariz, CPAP o un dispositivo oral, siempre elegidas según dónde se cierra tu vía aérea y qué estás dispuesto a usar.</p>",
  [("¿Roncar es peligroso?", "El ronquido simple no, pero puede ser la señal de una apnea del sueño, que sí tiene consecuencias para el corazón, la presión y la concentración. Un estudio del sueño en casa lo aclara."),
   ("¿Existe una cirugía para dejar de roncar?", "Sí, cuando la causa está en la nariz o en el paladar y el estudio lo respalda. No todas las personas son candidatas, y la Dra. es clara en eso desde la primera consulta."),
   ("¿Los niños deben roncar?", "No. El ronquido frecuente en un niño merece revisión: suele deberse a amígdalas o adenoides grandes y afecta su descanso, su conducta y su crecimiento.")],
  [AASM("Clinical Practice Guideline for Diagnostic Testing for Adult Obstructive Sleep Apnea", "2017"), AAO("Tonsillectomy in Children", "2019"), SMORL],
  ["estudio-del-sueno", "cirugia-de-ronquido-y-apnea", "septoplastia"], ("apnea-obstructiva-del-sueno", "desviacion-de-tabique-nasal", "amigdalitis"))

C("apnea-obstructiva-del-sueno", "Apnea obstructiva del sueño", "sueno", "sueno",
  "Qué es, cómo se diagnostica y qué opciones de tratamiento existen, explicado por una otorrinolaringólogo con subespecialidad en desórdenes respiratorios del sueño.",
  "<p>En la apnea obstructiva del sueño, la vía aérea se cierra una y otra vez mientras duermes. Cada cierre interrumpe la respiración durante unos segundos, baja el oxígeno y obliga al cerebro a despertarte brevemente para volver a respirar. Son despertares que no recuerdas, pero que fragmentan el sueño cientos de veces por noche: por eso te levantas cansado aunque hayas dormido «ocho horas».</p><p>No tratarla tiene consecuencias: presión alta, mayor riesgo cardiovascular, somnolencia al manejar, problemas de concentración y de estado de ánimo. La buena noticia es que se diagnostica con un estudio sencillo que puedes hacer en tu propia cama, y que hoy existen varios tratamientos efectivos que se eligen según la causa de la obstrucción y tus preferencias.</p>",
  ["Ronquido fuerte con pausas que otros notan", "Sueño no reparador y somnolencia durante el día", "Dolor de cabeza al despertar y boca seca", "Despertares con sensación de ahogo", "Dificultad para concentrarse, irritabilidad y bajo rendimiento", "Levantarse varias veces a orinar por la noche"],
  ["Estrechez de la vía aérea por anatomía: paladar, lengua, amígdalas, mandíbula pequeña", "Obstrucción nasal", "Sobrepeso y obesidad", "Edad, sexo masculino y menopausia en mujeres", "Alcohol, sedantes y dormir boca arriba, que la empeoran"],
  ["Si roncas y alguien ha visto que dejas de respirar", "Si te despiertas cansado a pesar de dormir suficiente", "Si tienes presión alta difícil de controlar", "Si te quedas dormido viendo televisión, leyendo o manejando", "Si usas CPAP y no lo toleras: hay alternativas que valorar"],
  DX_SUENO + "<p>El estudio en casa registra tu respiración, el oxígeno, el ronquido y la posición durante una noche normal, y la Dra. lo interpreta personalmente para explicarte el resultado y graduar la apnea. Con eso, y con lo que vio en la exploración, define el tratamiento.</p>",
  "<p>La Dra. tiene subespecialidad en desórdenes respiratorios del sueño y aborda la apnea desde las dos vertientes: la médica, con CPAP, dispositivos orales y medidas, y la quirúrgica, con cirugía nasal y del paladar cuando la anatomía lo indica. Su papel es ayudarte a elegir el tratamiento que puedas sostener en el tiempo, porque la apnea se controla con constancia, y acompañarte hasta que duermas bien.</p>",
  [("¿El CPAP es la única opción?", "No. Es el tratamiento más efectivo para la apnea moderada y grave, pero existen alternativas: cirugía nasal o del paladar, dispositivos de avance mandibular, terapia posicional y control de peso. Se eligen según tu caso."),
   ("¿Puedo hacerme el estudio en casa?", "Sí. La poligrafía respiratoria en casa es el estudio de primera elección en la mayoría de los adultos con sospecha de apnea. La Dra. te presta el equipo, te explica cómo colocarlo y lo interpreta ella misma."),
   ("¿La apnea se cura?", "Depende de la causa. Cuando es por amígdalas grandes o una obstrucción corregible, la cirugía puede resolverla. En otros casos se controla de forma efectiva con tratamiento continuo, igual que la presión alta."),
   ("¿Los niños pueden tener apnea?", "Sí, casi siempre por amígdalas y adenoides grandes. La Dra. valora casos pediátricos seleccionados y, cuando conviene, se coordina con pediatría.")],
  [AASM("Clinical Practice Guideline for Diagnostic Testing for Adult Obstructive Sleep Apnea", "2017"), AASM("Treatment of Adult Obstructive Sleep Apnea with Positive Airway Pressure", "2019"), SMORL],
  ["estudio-del-sueno", "cpap", "cirugia-de-ronquido-y-apnea", "dispositivo-de-avance-mandibular"], ("ronquido", "desviacion-de-tabique-nasal"))

# =============================================================== TRATAMIENTOS =====
RIESGOS_CX = "<p>Como toda cirugía, tiene riesgos: sangrado, infección, molestias por la anestesia y la posibilidad de que la mejoría sea parcial o de que haga falta un procedimiento adicional. La Dra. te explica los riesgos específicos de tu caso y las alternativas antes de que decidas, y entrega el consentimiento informado por escrito.</p>"

T("septoplastia", "Septoplastia", "orl", "nariz", "cirugia", "ofrece",
  "Cirugía que corrige la desviación del tabique nasal para mejorar el paso del aire. Se realiza por dentro de la nariz, sin cicatrices visibles.",
  "<p>La septoplastia endereza el tabique nasal. Se trabaja por dentro de la nariz: se levanta la mucosa, se retira o remodela la parte desviada del cartílago y el hueso, y se vuelve a colocar la mucosa en su sitio. No cambia la forma externa de la nariz ni deja cicatrices visibles.</p><p>Con frecuencia se combina con una turbinoplastia, porque el cornete del lado más abierto suele haber crecido para compensar, y con cirugía de los senos paranasales cuando hay sinusitis crónica. Si además quieres mejorar la forma de la nariz, se planea como rinoplastia funcional.</p>",
  ["Obstrucción nasal por tabique desviado que no mejora con tratamiento médico", "Ronquido o apnea en los que la nariz es parte de la obstrucción", "Sinusitis de repetición favorecida por la desviación", "Sangrados nasales por una zona del tabique expuesta"],
  "<p>Valoración en consultorio con endoscopia nasal para confirmar que el tabique es la causa y revisar cornetes y senos. Tomografía cuando hace falta ver la anatomía completa o hay sinusitis asociada. Estudios preoperatorios de laboratorio y valoración de anestesia.</p>",
  "<p>Se realiza en hospital, en quirófano, habitualmente con anestesia general y en un procedimiento ambulatorio o con una noche de estancia según el caso. Al terminar, la Dra. coloca férulas internas blandas o un taponamiento ligero que se retira en consulta a los pocos días.</p>",
  "<p>Los primeros días hay congestión y sensación de nariz tapada, que mejora al retirar las férulas. La mayoría de las personas retoma actividades ligeras en pocos días y evita ejercicio intenso y sonarse con fuerza durante las primeras semanas. La Dra. entrega indicaciones por escrito y revisa la cicatrización en consulta.</p>",
  RIESGOS_CX + "<p>Alternativas: tratamiento médico de la rinitis asociada, turbinoplastia sola cuando los cornetes son la causa principal, o manejo del ronquido por otras vías si la nariz no es el origen.</p>",
  "<p>La Dra. decide operar cuando la exploración y los estudios muestran que el tabique es de verdad la causa de la obstrucción, y planea la cirugía como parte de un plan para que respires bien: nariz, cornetes y, cuando aplica, el sueño. Si quieres cambiar también la forma de la nariz, lo conversan desde la primera consulta para planear un solo procedimiento.</p>",
  [("¿Me van a romper la nariz?", "No. La septoplastia se hace por dentro, sin fracturar los huesos nasales. Eso corresponde a la rinoplastia, que es otro procedimiento."),
   ("¿Duele?", "Las molestias principales son congestión y presión, más que dolor, y se controlan con los analgésicos indicados."),
   ("¿Cuándo vuelvo a respirar bien?", "La mejoría se nota al retirar las férulas y va aumentando conforme baja la inflamación en las semanas siguientes.")],
  [SMORL, AAO("Improving Nasal Form and Function after Rhinoplasty", "2017")], ["desviacion-de-tabique-nasal"], ("turbinoplastia", "rinoplastia", "ronquido"))

T("turbinoplastia", "Turbinoplastia", "orl", "nariz", "cirugia", "ofrece",
  "Reducción de los cornetes nasales cuando crecen y obstruyen la nariz, con frecuencia por rinitis crónica.",
  "<p>Los cornetes son estructuras dentro de la nariz que calientan y humedecen el aire que respiras. Cuando están inflamados durante mucho tiempo, como en la rinitis crónica, crecen y bloquean el paso del aire aun con tratamiento. La turbinoplastia reduce su tamaño conservando su función: se retira parte del tejido interno y se respeta la mucosa, para que la nariz siga haciendo su trabajo.</p><p>Es un procedimiento conservador, se realiza por dentro de la nariz y con frecuencia se combina con la septoplastia.</p>",
  ["Nariz tapada por cornetes grandes que no responde a medicamentos", "Rinitis crónica con obstrucción persistente", "Dependencia de sprays descongestionantes", "Ronquido en el que la obstrucción nasal es parte del problema"],
  "<p>Endoscopia nasal en consultorio para confirmar que los cornetes son la causa, y prueba de respuesta al tratamiento médico. Tomografía cuando se combina con septoplastia o hay sinusitis. Estudios preoperatorios y valoración de anestesia.</p>",
  "<p>En quirófano, con anestesia general o local con sedación según el caso, de forma ambulatoria. La Dra. reduce el cornete con técnica que preserva la mucosa. Cuando se combina con septoplastia, se realiza en el mismo tiempo quirúrgico.</p>",
  "<p>Congestión y costras durante las primeras semanas, que se manejan con lavados nasales. Las actividades cotidianas se retoman en pocos días. La Dra. revisa en consulta y limpia la nariz bajo endoscopia cuando hace falta.</p>",
  RIESGOS_CX + "<p>Alternativas: continuar con tratamiento médico de la rinitis, inmunoterapia en rinitis alérgica, o septoplastia si el tabique es el problema principal.</p>",
  "<p>La Dra. prefiere técnicas conservadoras que reduzcan el cornete sin dañar la mucosa, porque una nariz que respira debe seguir humedeciendo y filtrando el aire. Por eso valora primero el tratamiento médico y opera cuando la obstrucción persiste a pesar de él.</p>",
  [("¿Se quitan los cornetes?", "No. Se reduce su tamaño conservando su función. Retirarlos por completo causa problemas de resequedad, y por eso no se hace."),
   ("¿La rinitis desaparece con la cirugía?", "La obstrucción mejora de forma clara. La tendencia alérgica puede seguir dando estornudos o escurrimiento, que se controlan con tratamiento."),
   ("¿Puede volver a crecer el cornete?", "Puede recuperar algo de volumen con los años si la inflamación continúa, por eso se acompaña de tratamiento de la rinitis.")],
  [ARIA, SMORL], ["rinitis"], ("septoplastia", "sinusitis"))

T("amigdalas-y-adenoides", "Cirugía de amígdalas y adenoides", "orl", "garganta", "cirugia", "ofrece",
  "Amigdalectomía y adenoidectomía: retiro de amígdalas y adenoides cuando causan infecciones repetidas u obstruyen la respiración, sobre todo en niños.",
  "<p>La amigdalectomía retira las amígdalas; la adenoidectomía, las adenoides, que son tejido similar ubicado detrás de la nariz. Se realizan juntas o por separado según lo que cause el problema. Es una de las cirugías más frecuentes en niños y tiene dos indicaciones principales: infecciones de garganta que se repiten demasiado y amígdalas o adenoides grandes que obstruyen la respiración durante el sueño.</p><p>En adultos se indica por amigdalitis de repetición, abscesos o cuando las amígdalas contribuyen a la apnea del sueño.</p>",
  ["Amigdalitis de repetición que afecta la vida escolar o laboral", "Amígdalas o adenoides grandes con ronquido, pausas o apnea en niños", "Respiración por la boca constante y otitis de repetición por adenoides", "Absceso periamigdalino previo", "Adultos con apnea del sueño en los que las amígdalas son parte de la obstrucción"],
  "<p>Valoración en consultorio con exploración de garganta y, cuando hace falta ver las adenoides, endoscopia nasal. Estudio de imagen solo si se requiere. En niños con ronquido, la Dra. puede indicar un estudio del sueño en casa para documentar la apnea. Estudios de laboratorio y valoración de anestesia antes de la cirugía.</p>",
  "<p>En hospital, bajo anestesia general, en un procedimiento que suele ser ambulatorio o con una noche de observación según la edad y el caso. Se realiza por la boca, sin incisiones externas. La Dra. explica a los padres cada paso y qué esperar al despertar.</p>",
  "<p>El dolor de garganta es lo esperado durante una a dos semanas y se controla con analgésicos pautados, buena hidratación y alimentos suaves y fríos. Es normal que la voz suene distinta unos días y que haya mal aliento mientras cicatriza. La Dra. entrega indicaciones por escrito, revisa en consulta y está disponible ante cualquier duda; el sangrado después de la cirugía es poco frecuente pero debe atenderse de inmediato.</p>",
  RIESGOS_CX + "<p>Alternativas: tratamiento médico de cada episodio y vigilancia, tratamiento de la rinitis cuando las adenoides se inflaman por alergia, y en apnea leve, observación con seguimiento.</p>",
  "<p>La Dra. opera amígdalas cuando los criterios se cumplen y no antes. Lo que más le importa es que los padres salgan del consultorio entendiendo por qué sí o por qué no, y que el postoperatorio esté bien acompañado con indicaciones claras.</p>",
  [("¿A qué edad se puede operar?", "No hay una edad mínima fija; depende del motivo. En niños pequeños con apnea por amígdalas grandes, la cirugía puede indicarse temprano. La Dra. lo valora caso por caso."),
   ("¿Cuántos días falta a la escuela?", "En general entre una y dos semanas, según la recuperación. El ejercicio intenso se retoma cuando la Dra. lo indica."),
   ("¿Qué puede comer después?", "Alimentos suaves, fríos o tibios y mucha agua. Lo importante es que coma y tome líquidos, aunque sea poco y seguido.")],
  [AAO("Tonsillectomy in Children", "2019"), SMORL], ["amigdalitis"], ("ronquido", "otitis"))

T("cirugia-endoscopica-nasal", "Cirugía endoscópica nasal", "orl", "nariz", "cirugia", "ofrece",
  "Cirugía de los senos paranasales por vía endoscópica, sin incisiones externas, para sinusitis crónica o pólipos.",
  "<p>La cirugía endoscópica de senos paranasales se realiza por dentro de la nariz con una cámara y pinzas finas. Abre las vías por las que drenan los senos, retira pólipos y tejido inflamado y permite que los medicamentos y los lavados lleguen a donde deben. No deja cicatrices ni cambia la forma de la nariz.</p><p>Está indicada cuando la sinusitis crónica o los pólipos no responden al tratamiento médico bien llevado. La tomografía previa es el mapa de la cirugía y se revisa contigo antes de operar.</p>",
  ["Sinusitis crónica que persiste a pesar del tratamiento médico", "Pólipos nasales que obstruyen y quitan el olfato", "Sinusitis agudas que se repiten varias veces al año", "Complicaciones o causas anatómicas que bloquean el drenaje"],
  "<p>Endoscopia nasal en consultorio, tratamiento médico completo previo y tomografía de senos paranasales, indispensable para planear la cirugía. Estudios de laboratorio y valoración de anestesia.</p>",
  "<p>En hospital, bajo anestesia general. La Dra. trabaja con endoscopio e instrumentos finos dentro de la nariz, abriendo los senos afectados según la tomografía. Con frecuencia se combina con septoplastia o turbinoplastia. Puede ser ambulatoria o con una noche de estancia.</p>",
  "<p>Congestión, costras y algo de sangrado ligero los primeros días. Los lavados nasales son la parte más importante de la recuperación, y las limpiezas endoscópicas en consulta ayudan a que cicatrice bien. Actividades ligeras en pocos días; ejercicio intenso y vuelos, cuando la Dra. lo indique.</p>",
  RIESGOS_CX + "<p>Por la cercanía con el ojo y la base del cráneo, la cirugía se planea con la tomografía y técnica cuidadosa. Alternativas: continuar con tratamiento médico y lavados, tratamientos biológicos en casos seleccionados de pólipos.</p>",
  "<p>La Dra. opera cuando el tratamiento médico ya dio lo que podía dar. Después de la cirugía, el seguimiento y el tratamiento de mantenimiento son parte del plan, porque en sinusitis crónica y pólipos la mejoría dura cuando se cuida.</p>",
  [("¿Es una cirugía grande?", "Es una cirugía mayor que se hace por vía mínimamente invasiva: sin incisiones externas y con recuperación en días, no en semanas."),
   ("¿Volveré a oler?", "En muchos casos el olfato mejora notablemente, sobre todo en pólipos. La Dra. te orienta sobre qué esperar según tu caso."),
   ("¿Necesito seguir tratamiento después?", "Sí. Los lavados y el tratamiento de mantenimiento ayudan a que el resultado dure y reducen las recaídas.")],
  [EPOS, AAO("Adult Sinusitis", "2015"), SMORL], ["sinusitis", "polipos-nasales"], ("septoplastia", "rinitis"))

T("rinoplastia", "Rinoplastia funcional", "orl", "nariz", "cirugia", "ofrece",
  "Cirugía de nariz que mejora la respiración y, cuando se desea, la forma. Septoplastia, turbinoplastia y rinoplastia planeadas en un solo procedimiento para que la nariz funcione y se vea bien.",
  "<p>La rinoplastia funcional corrige la estructura de la nariz para que respires mejor y, al mismo tiempo, atiende la forma cuando así lo deseas. Como otorrinolaringólogo, la Dra. parte de la función: tabique, cornetes y válvula nasal. Sobre esa base se planea el cambio estético, de modo que el resultado se vea natural y la nariz siga respirando bien.</p><p>Es una cirugía que se planea con calma: la Dra. conversa contigo sobre qué te molesta, qué es posible y qué esperar, y lo revisa con fotografías y exploración antes de proponer un plan.</p>",
  ["Obstrucción nasal con o sin deseo de cambio estético", "Secuelas de golpes o fracturas nasales", "Rinoplastia previa con problemas para respirar", "Nariz que respira mal y cuya forma también quieres mejorar"],
  "<p>Valoración en consultorio con endoscopia nasal y fotografías, y tomografía cuando hace falta conocer la anatomía interna. Estudios de laboratorio y valoración de anestesia. La Dra. explica con claridad qué cambios son realistas.</p>",
  "<p>En hospital, bajo anestesia general. Según el caso se trabaja por dentro de la nariz o con una pequeña incisión en la columela. Se corrige el tabique, se reducen los cornetes si es necesario y se remodela la estructura. Al terminar se coloca una férula externa y, en ocasiones, férulas internas.</p>",
  "<p>Moretones e hinchazón los primeros días, que ceden en una a dos semanas; la férula se retira en consulta. La forma definitiva se aprecia conforme baja la inflamación a lo largo de los meses. Actividades ligeras en pocos días; deporte y lentes sobre la nariz, cuando la Dra. lo indique.</p>",
  RIESGOS_CX + "<p>En rinoplastia es importante saber que el resultado estético final tarda meses en apreciarse y que un pequeño porcentaje de casos puede requerir un retoque. Alternativas: septoplastia y turbinoplastia solas cuando lo que buscas es solo respirar mejor.</p>",
  "<p>Para la Dra., una nariz bonita que no respira no es un buen resultado. Por eso planea cada rinoplastia desde la función y con expectativas honestas, y te acompaña en una recuperación que requiere paciencia.</p>",
  [("¿La diferencia entre septoplastia y rinoplastia?", "La septoplastia corrige solo el tabique por dentro y no cambia la forma. La rinoplastia modifica la estructura externa de la nariz; la funcional hace ambas cosas en un mismo procedimiento."),
   ("¿Cuándo se ve el resultado?", "La respiración mejora en semanas. La forma se aprecia de manera progresiva conforme baja la inflamación, y el resultado final tarda varios meses."),
   ("¿Quedan cicatrices?", "En la técnica cerrada no hay cicatrices visibles. En la abierta queda una pequeña cicatriz en la columela que suele ser poco perceptible con el tiempo.")],
  [AAO("Improving Nasal Form and Function after Rhinoplasty", "2017"), SMORL], ["desviacion-de-tabique-nasal"], ("septoplastia", "turbinoplastia"))

T("estudio-del-sueno", "Estudio del sueño en casa", "sueno", "sueno", "estudio", "ofrece",
  "Poligrafía respiratoria realizada en tu propia cama e interpretada por la propia Dra.: registra respiración, oxígeno y ronquido durante la noche para confirmar y graduar la apnea.",
  "<p>El estudio del sueño en casa, o poligrafía respiratoria, registra durante una noche el flujo de aire por la nariz, el esfuerzo respiratorio, el nivel de oxígeno en la sangre, el ronquido, la frecuencia cardiaca y la posición en la que duermes. Es un equipo pequeño que te colocas antes de dormir y que la Dra. te enseña a usar en consulta.</p><p>Es el estudio de primera elección para confirmar la apnea obstructiva del sueño en la mayoría de los adultos, porque mide lo que importa en una noche normal de tu vida, no en un laboratorio. La Dra. lo interpreta personalmente y te explica el resultado.</p>",
  ["Ronquido con pausas en la respiración", "Somnolencia o cansancio durante el día", "Antes de decidir un tratamiento de ronquido o apnea", "Para verificar el resultado de un tratamiento (CPAP, cirugía, dispositivo oral)", "Presión alta difícil de controlar o diagnóstico previo de arritmias"],
  "<p>Consulta de valoración con exploración y endoscopia de la vía aérea. La Dra. revisa tus cuestionarios de somnolencia y riesgo, y decide si el estudio en casa es el adecuado o si tu caso requiere polisomnografía en laboratorio, que indica cuando hay sospecha de otros trastornos del sueño o enfermedades asociadas.</p>",
  "<p>Recoges el equipo en consultorio con instrucciones por escrito, te lo colocas en casa a la hora habitual de dormir y lo devuelves al día siguiente. La Dra. descarga y analiza el registro y te cita para explicarte el resultado y el plan de tratamiento.</p>",
  "<p>No hay recuperación: es un estudio sin molestias y sin medicamentos. Al día siguiente haces tu vida normal.</p>",
  "<p>Es un estudio seguro. Su limitación es que en algunos casos la noche no es representativa (sensores que se desplazan, insomnio esa noche) y hay que repetirlo, o que el caso requiera polisomnografía completa en laboratorio.</p>",
  "<p>La Dra. realiza e interpreta el estudio ella misma, sin intermediarios: eso permite que el resultado se traduzca en un plan concreto en la misma consulta de revisión. Y si tu caso necesita un estudio en laboratorio, te lo indica con claridad.</p>",
  [("¿Es lo mismo que una polisomnografía?", "No. La polisomnografía se hace en un laboratorio de sueño con registro de la actividad cerebral. El estudio en casa es más sencillo y registra lo respiratorio; es suficiente para diagnosticar apnea obstructiva en la mayoría de los adultos."),
   ("¿Duermo igual con el equipo puesto?", "El equipo es ligero y la mayoría de las personas duerme con normalidad. Si una noche no es representativa, se repite."),
   ("¿Qué pasa después del estudio?", "La Dra. te cita para revisar los resultados y proponer el tratamiento según el grado de apnea y lo que encontró en la exploración.")],
  [AASM("Clinical Practice Guideline for Diagnostic Testing for Adult Obstructive Sleep Apnea", "2017")], ["ronquido", "apnea-obstructiva-del-sueno"], ("cpap", "cirugia-de-ronquido-y-apnea"))

T("cpap", "CPAP", "sueno", "sueno", "terapia", "ofrece",
  "Equipo que mantiene abierta la vía aérea con presión de aire durante el sueño. La Dra. lo indica, ajusta la presión y da seguimiento para lograr una buena adaptación y uso constante.",
  "<p>El CPAP es un equipo pequeño que envía aire a presión suave a través de una mascarilla mientras duermes. Esa presión funciona como una férula de aire que impide que la vía aérea se cierre, elimina las pausas y el ronquido y permite que el sueño por fin sea reparador. Es el tratamiento más efectivo para la apnea obstructiva moderada y grave.</p><p>El reto del CPAP no es que funcione, sino que lo uses. Por eso el acompañamiento en las primeras semanas, la elección de la mascarilla y el ajuste de la presión hacen la diferencia entre un equipo guardado en el clóset y una persona que vuelve a dormir bien.</p>",
  ["Apnea obstructiva del sueño confirmada por estudio, moderada o grave", "Apnea leve con síntomas importantes o enfermedades asociadas", "Personas que no son candidatas a cirugía o prefieren un tratamiento no quirúrgico", "Pacientes que ya usan CPAP y no se adaptan: hay mucho que ajustar"],
  "<p>Estudio del sueño en casa que confirme y gradúe la apnea, y exploración de la nariz y la vía aérea: una nariz obstruida es la causa más frecuente de no tolerar el CPAP y se puede tratar.</p>",
  "<p>La Dra. indica el tipo de equipo y de mascarilla según tu anatomía y tus hábitos, ajusta la presión (por titulación automática o con estudio) y te cita en las primeras semanas para resolver molestias: fugas, resequedad, presión alta o baja. Los equipos modernos registran el uso y permiten ajustar a distancia.</p>",
  "<p>No hay recuperación. La adaptación suele tomar algunas semanas; durante ese tiempo el seguimiento cercano es parte del tratamiento. Muchas personas notan la diferencia en su energía desde las primeras noches de uso completo.</p>",
  "<p>El CPAP es seguro. Las molestias habituales son resequedad, marcas de la mascarilla o sensación de presión, y todas tienen solución con ajustes. Alternativas cuando no se tolera: cirugía nasal o del paladar, dispositivo de avance mandibular o terapia posicional, según el estudio y la exploración.</p>",
  "<p>La Dra. no entrega un equipo y se despide. Acompaña la adaptación, trata la nariz si es lo que impide tolerarlo y, cuando después de intentarlo el CPAP no es para ti, te propone alternativas con la misma honestidad.</p>",
  [("¿Tendré que usarlo toda la vida?", "Mientras la apnea esté presente, sí, igual que un tratamiento para la presión. Si la causa cambia (peso, cirugía), se reevalúa con un nuevo estudio."),
   ("¿Puedo viajar con el CPAP?", "Sí. Los equipos son compactos y se permiten en cabina. La Dra. te orienta sobre cómo llevarlo."),
   ("No tolero la mascarilla, ¿qué hago?", "No lo abandones sin consultar. Cambiar de mascarilla, ajustar la presión o tratar la nariz resuelve la mayoría de los problemas de adaptación.")],
  [AASM("Treatment of Adult Obstructive Sleep Apnea with Positive Airway Pressure", "2019")], ["apnea-obstructiva-del-sueno"], ("estudio-del-sueno", "dispositivo-de-avance-mandibular", "cirugia-de-ronquido-y-apnea"))

T("cirugia-de-ronquido-y-apnea", "Cirugía de ronquido y apnea", "sueno", "sueno", "cirugia", "ofrece",
  "Faringoplastia y cirugía nasal para ensanchar la vía aérea cuando la anatomía lo indica. La endoscopia de sueño ayuda a localizar dónde se cierra.",
  "<p>La cirugía del ronquido y la apnea busca ensanchar y dar firmeza a la parte de la vía aérea que se cierra al dormir. No es una sola operación: puede ser cirugía nasal (septoplastia, turbinoplastia), cirugía del paladar como la <strong>faringoplastia con suturas barbadas</strong>, que reposiciona y tensa el paladar blando sin cortar tejido, retiro de amígdalas, o una combinación de ellas.</p><p>La clave está en elegir bien. Por eso la Dra. realiza una endoscopia de sueño (DISE) en quirófano, bajo sedación, para ver con exactitud dónde y cómo se cierra tu vía aérea mientras duermes, y propone la cirugía solo cuando la anatomía tiene una solución quirúrgica.</p>",
  ["Ronquido o apnea con obstrucción localizada en paladar o nariz", "Personas que no toleran el CPAP, según valoración", "Amígdalas grandes que contribuyen a la apnea", "Obstrucción nasal que impide usar el CPAP o lo hace ineficaz"],
  "<p>Estudio del sueño en casa para graduar la apnea, exploración y endoscopia en consultorio, y endoscopia de sueño (DISE) en quirófano para localizar el sitio de obstrucción. Tomografía cuando la nariz es parte del plan. Estudios de laboratorio y valoración de anestesia.</p>",
  "<p>En hospital, bajo anestesia general. Según el plan, la Dra. corrige la nariz, realiza la faringoplastia con suturas barbadas y, si aplica, retira las amígdalas en el mismo tiempo. La estancia suele ser de una noche.</p>",
  "<p>Dolor de garganta durante una a dos semanas en la cirugía del paladar, controlado con analgésicos y alimentación suave; congestión en la cirugía nasal. La Dra. revisa en consulta y, pasados unos meses, repite el estudio del sueño en casa para medir el resultado.</p>",
  RIESGOS_CX + "<p>En cirugía de apnea, la mejoría puede ser parcial y en algunos casos se combina con CPAP a menor presión o con un dispositivo oral. Alternativas: CPAP, dispositivo de avance mandibular, terapia posicional y control de peso.</p>",
  "<p>La Dra. tiene formación específica en cirugía de sueño y es miembro de la Sociedad Iberoamericana de Cirugía de Sueño. Su criterio es claro: operar a quien la anatomía lo permite y decírselo con honestidad a quien no, para que cada persona tenga el tratamiento que de verdad le funcione.</p>",
  [("¿La cirugía cura la apnea?", "En casos bien seleccionados, sobre todo con obstrucción localizada, puede resolverla o reducirla mucho. En otros, mejora el ronquido y facilita tolerar el CPAP. La endoscopia de sueño ayuda a predecir el resultado."),
   ("¿Qué es la endoscopia de sueño (DISE)?", "Un estudio breve en quirófano en el que, bajo sedación que simula el sueño, la Dra. observa con un endoscopio dónde se cierra tu vía aérea. Es la base para decidir qué operar."),
   ("¿Puedo operarme si no quiero usar CPAP?", "Depende de tu anatomía y del grado de apnea. La Dra. te dice con claridad si eres candidato después del estudio y la endoscopia de sueño.")],
  [AASM("Referral of Adults with Obstructive Sleep Apnea for Surgical Consultation", "2021"), SMORL], ["ronquido", "apnea-obstructiva-del-sueno"], ("septoplastia", "amigdalas-y-adenoides", "cpap"))

T("dispositivo-de-avance-mandibular", "Dispositivo de avance mandibular", "sueno", "sueno", "terapia", "refiere",
  "Férula que adelanta la mandíbula durante el sueño para abrir la vía aérea. La Dra. lo indica cuando conviene y te refiere con una odontóloga especializada en sueño para su fabricación y ajuste.",
  "<p>El dispositivo de avance mandibular es una férula hecha a medida, parecida a un protector bucal, que mantiene la mandíbula ligeramente adelantada mientras duermes. Al hacerlo, la lengua y el paladar se desplazan hacia adelante y la vía aérea se abre, lo que reduce el ronquido y las apneas.</p><p>Es una alternativa al CPAP en ronquido y apnea leve a moderada, y en personas que no toleran el CPAP. La Dra. valora si eres candidato y, cuando lo indica, te refiere con una odontóloga especializada en sueño que fabrica y ajusta el dispositivo; después, la Dra. verifica el resultado con un estudio del sueño.</p>",
  ["Ronquido o apnea leve a moderada, según valoración", "Personas que no toleran el CPAP", "Como complemento a otras medidas cuando el estudio lo respalda"],
  "<p>Estudio del sueño en casa y exploración de la vía aérea por la Dra. para confirmar que el dispositivo es una buena opción. Revisión dental para asegurar que hay dientes y articulación en condiciones de usarlo.</p>",
  "<p>La odontóloga toma impresiones y fabrica el dispositivo a medida, y lo ajusta de forma progresiva en varias citas hasta encontrar el avance que funciona sin molestias. La Dra. coordina el proceso y, una vez ajustado, repite el estudio del sueño en casa para medir el resultado.</p>",
  "<p>No hay recuperación. En las primeras semanas puede haber molestia en los dientes o la mandíbula al despertar, que suele ceder con los ajustes.</p>",
  "<p>Es un tratamiento seguro. Con el uso prolongado pueden aparecer cambios leves en la mordida, por lo que el seguimiento dental es parte del plan. Alternativas: CPAP, cirugía nasal o del paladar, terapia posicional.</p>",
  "<p>La Dra. trabaja en equipo: indica el dispositivo cuando el estudio y la exploración lo respaldan, refiere con una odontóloga especializada en sueño y se queda a cargo de verificar que funcione. Así, el tratamiento no se queda en una férula sino en un resultado medido.</p>",
  [("¿Sirve cualquier férula de farmacia?", "No. Las férulas genéricas no se ajustan ni se gradúan y pueden dañar la mordida. El dispositivo eficaz se fabrica a medida y lo ajusta un profesional."),
   ("¿Es tan efectivo como el CPAP?", "En apnea leve a moderada puede ser comparable porque se usa más horas. En apnea grave el CPAP sigue siendo el tratamiento de elección."),
   ("¿Quién lo hace?", "La Dra. te refiere con una odontóloga especializada en sueño. Ella fabrica y ajusta el dispositivo; la Dra. mide el resultado con un nuevo estudio.")],
  [AASM("Clinical Practice Guideline for the Treatment of Obstructive Sleep Apnea and Snoring with Oral Appliance Therapy", "2015")], ["ronquido", "apnea-obstructiva-del-sueno"], ("cpap", "estudio-del-sueno"))

out = {"condicion": cond, "tratamiento": trat}
pathlib.Path(__file__).with_name("medical-drafts.json").write_text(json.dumps(out, ensure_ascii=False, indent=1), encoding="utf-8")
print("ok", len(cond), "condiciones", len(trat), "tratamientos")

# Recursos (artículos) solicitados por la Dra. en el briefing; esqueleto para que ella dicte el contenido.
rec = [
 dict(slug="como-limpiar-los-oidos", titulo="Cómo limpiar los oídos sin lastimarlos", excerpt="El cerumen no es suciedad: protege el conducto auditivo. El problema aparece cuando intentamos sacarlo con cotonetes.",
  html="<h2>Qué hace el cerumen</h2><p>Texto pendiente de la Dra.</p><h2>Por qué los cotonetes empeoran el tapón</h2><p>Texto pendiente de la Dra.</p><h2>Qué sí puedes hacer en casa</h2><p>Texto pendiente de la Dra.</p><p><strong>Borrador pendiente de revisión médica.</strong></p>"),
 dict(slug="postoperatorio-de-amigdalas", titulo="Cómo es el postoperatorio de amígdalas", excerpt="Qué esperar día a día después de una cirugía de amígdalas y adenoides, y cómo ayudar a tu hijo a pasarlo mejor.",
  html="<h2>Los primeros días</h2><p>Texto pendiente de la Dra.</p><h2>Qué comer y qué evitar</h2><p>Texto pendiente de la Dra.</p><h2>Señales para llamar</h2><p>Texto pendiente de la Dra.</p><p><strong>Borrador pendiente de revisión médica.</strong></p>"),
 dict(slug="como-limpiar-la-nariz", titulo="Cómo limpiar la nariz: lavados nasales bien hechos", excerpt="El lavado nasal es una de las medidas más efectivas y seguras para rinitis y sinusitis, siempre que se haga bien.",
  html="<h2>Qué necesitas</h2><p>Texto pendiente de la Dra.</p><h2>Paso a paso</h2><p>Texto pendiente de la Dra.</p><h2>Errores frecuentes</h2><p>Texto pendiente de la Dra.</p><p><strong>Borrador pendiente de revisión médica.</strong></p>"),
]
pathlib.Path(__file__).with_name("recursos-drafts.json").write_text(json.dumps(rec, ensure_ascii=False, indent=1), encoding="utf-8")
print("ok recursos", len(rec))
